---
title: "Part 1 - Stringr"
author: "Laurel Abowd"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


### Detect string patternns wiht 'str_detect()'

```{r}
vec <- c(" A Unicorn   Fish", "add    cornmeal  ", "French FRIES", "acorn Squash ")

str_detect(vec, pattern = "corn")
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))

# could also use str_subset() instead of filter(str_detect())
```

### Replace a string patter with something else with 'str_replace'


```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")

vec_bren
```
replace the pattern "Sky" with the pattern "TORNADO" 

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

## Use 'str_trim()' to remove excess leading and trailing whitespace
```{r}
str_trim(vec)

str_squish(vec)
```
- 'str_ti_*()'

```{r}
str_to_lower(vec)

str_to_upper(vec)

str_to_title(vec)
```

Using these in combination 

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))
```

